import streamlit as st
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage
# Import our new agent from Agent.py
from Agent import agent

st.set_page_config(page_title="City Intelligence Agent", page_icon="🏙️")
st.title("🏙️ City Intelligence System")
st.markdown("Ask me about the **weather** or **latest news** in any city!")

# Initialize chat history in Streamlit session state
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display previous chat messages from history on app rerun
for message in st.session_state.messages:
    if isinstance(message, HumanMessage):
        with st.chat_message("user"):
            st.markdown(message.content)
    elif isinstance(message, AIMessage) and message.content:
        # Only print AIMessages if they have text content
        with st.chat_message("assistant"):
            st.markdown(message.content)

# React to user input
if prompt := st.chat_input("What would you like to know?"):
    # Display user message in chat message container
    with st.chat_message("user"):
        st.markdown(prompt)
    
    # Add user message to chat history
    st.session_state.messages.append(HumanMessage(content=prompt))

    with st.spinner("Thinking..."):
        # Record how many messages we had before this turn
        initial_length = len(st.session_state.messages)
        
        # Use the new agent to process the query
        result = agent.invoke({"messages": st.session_state.messages})
        
        # Get only the new messages generated by the agent during this turn
        new_messages = result["messages"][initial_length:]
        
        # Iterate through the new messages and display them in the UI
        for msg in new_messages:
            if isinstance(msg, AIMessage) and msg.tool_calls:
                for tool_call in msg.tool_calls:
                    with st.chat_message("assistant", avatar="⚙️"):
                        st.markdown(f"*Running {tool_call['name']}...*")
            
            elif isinstance(msg, ToolMessage):
                with st.chat_message("assistant", avatar="🛠️"):
                    with st.expander("Tool Output"):
                        st.markdown(msg.content)
            
            elif isinstance(msg, AIMessage) and msg.content:
                with st.chat_message("assistant"):
                    st.markdown(msg.content)
        
        # Update the session state history with all new messages
        st.session_state.messages.extend(new_messages)
